name: Deploy VitePress site to Pages

on:
  push:
    branches:
      - main         # Spustí workflow pro větve 'main'
      - maintenance  # Spustí workflow pro větev 'maintenance'
  workflow_dispatch:  # Umožní ruční spuštění workflow
    inputs:
      mode:
        description: "Deployment mode: 'normal' or 'maintenance'"
        required: true
        default: "normal"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the site
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build VitePress
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Cesta k souborům v rootu repozitáře

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: ${{ github.ref == 'refs/heads/maintenance' && 'maintenance' || 'main' }}  # Pokud je push na větev 'maintenance', nasadí údržbu
