name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      mode:
        description: "Deployment mode: 'normal' or 'maintenance'"
        required: true
        default: "normal"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    if: ${{ inputs.mode == 'normal' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    name: Build (Normal Mode)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Build VitePress site
        run: npm run docs:build
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # Nasazuje obsah z rootu, pokud je režim normal

  maintenance:
    if: ${{ inputs.mode == 'maintenance' }}
    runs-on: ubuntu-latest
    name: Deploy Maintenance Page
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Maintenance Page
        uses: actions/upload-pages-artifact@v3
        with:
          path: maintenance # Nasazuje obsah složky maintenance, pokud je režim údržby

  deploy:
    runs-on: ubuntu-latest
    needs: [build, maintenance]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
